### PR TITLE
Fixes for Darwin PPC32

### PR DESCRIPTION
**Pull request by evanmiller**
This PR consolidates some of @kernigh's work over in #211. It successfully compiles and runs the Fibonacci test, without a crash, on PPC32 hardware running Darwin 8:

```
$ ./a.out
0 1 1 2 3 5 8 13 21 34
main: done
$ uname -r
8.11.0
```

For `make_fcontext`, use the diff provided here:

https://github.com/boostorg/context/issues/211#issuecomment-1328154669

For `ontop_context`, adapt the Linux PPC32 fixes from here:

https://github.com/boostorg/context/commit/df8fb6b5289492914dd2af479e40e9737399fd21

### CODE REVIEW

**Comment by barracuda156** [comment]
@evanmiller Do you think we should first ensure that `fiber` does not fail with these changes? Given that is was building before with not fully fixed `context`, it presumably should build with the properly fixed one.

**Comment by evanmiller** [comment]
> @evanmiller Do you think we should first ensure that `fiber` does not fail with these changes? Given that is was building before with not fully fixed `context`, it presumably should build with the properly fixed one.

@barracuda156 Which compilers / Boost versions were successfully building Fiber on PPC? I encountered an issue with GCC7 / Boost 1.81 but I can't comment on any other combinations.

**Comment by barracuda156** [comment]
> > @evanmiller Do you think we should first ensure that `fiber` does not fail with these changes? Given that is was building before with not fully fixed `context`, it presumably should build with the properly fixed one.
> 
> @barracuda156 Which compilers / Boost versions were successfully building Fiber on PPC? I encountered an issue with GCC7 / Boost 1.81 but I can't comment on any other combinations.

Well, everything was building with my earlier minimal fixes to `context` (which are not sufficient, as we know now).

**Comment by evanmiller** [comment]
@barracuda156 If you were able to build everything before, why don't you try building Fiber with these proposed changes and report back?

**Comment by barracuda156** [comment]
> @barracuda156 If you were able to build everything before, why don't you try building Fiber with these proposed changes and report back?

@evanmiller I will do it soonish.

**Comment by olk** [comment]
ty

**Comment by barracuda156** [comment]
Now we have `ppc64` left to fix. And possibly `fiber` for both.

**Comment by barracuda156** [comment]
@evanmiller Could you remind, what prevented us from fixing `ppc64` along?

**Pull request merged**
