### PR TITLE
Select assembly sources via preprocessor

### PR DESCRIPTION
**Pull request by Kojoley**
* Fixes cross-compilation abi and binformat detection.
* `abi` and `binary-format` are now optional but can be used to override autodetection.

### CODE REVIEW

**Comment by olk** [comment]
I don't want a big commit containing changes for many different issues - please create one commit for one fix.

**Comment by Kojoley** [comment]
> I don't want a big commit containing changes for many different issues - please create one commit for one fix.

You mean pull request instead of commit? Because currently there is one commit for one thing and I have probably even split it too much.

**Comment by Kojoley** [comment]
I've removed CI changes from the PR, some of them I've submitted as separate PRs.

**Comment by Kojoley** [comment]
Ping

**Comment by olk** [comment]
ty

**Comment by olk** [comment]
I was forced to revert all you commits because the changes prevented the release (errors on selecting the correct source etc.)

**Comment by Kojoley** [comment]
> I was forced to revert all you commits because the changes prevented the release (errors on selecting the correct source etc.)

It was b2 bug (https://github.com/bfgroup/b2/pull/326), do you interested in trying this again?

**Pull request merged**
