### PR TITLE
Switch mips1 to mips

### PR DESCRIPTION
**Pull request by FlyGoat**

### CODE REVIEW

**Comment by FlyGoat** [comment]
These four PRs should be accepted together:
- https://github.com/boostorg/build/pull/375
- https://github.com/boostorg/config/pull/254
- https://github.com/boostorg/context/pull/93
- https://github.com/boostorg/log/pull/66

**Comment by FlyGoat** [comment]
And I need some suggestions on how to set default abi for mips as N64 when addressing-model is 64bit.

**Comment by olk** [comment]
In build/Jamfile something like:
```
local rule default_abi ( properties * )
{
    local tmp = sysv ;
    if [ os.name ] = "NT" { tmp = ms ; }
    else if [ os.name ] = "CYGWIN" { tmp = ms ; }
    else if [ os.platform ] = "ARM" { tmp = aapcs ; }
    else if ( [ os.platform ] = "MIPS" && <address-model>32 in $(properties) ) { tmp = o32 ; }
    else if ( [ os.platform ] = "MIPS" && <address-model>64 in $(properties) ) { tmp = n64 ; }
    return $(tmp) ;
}
```

**Comment by wzssyqa** [comment]
> 
> 
> In build/Jamfile something like:
> 
> ```
> local rule default_abi ( properties * )

in fact, here $(properties)  is empty.

> {
>     local tmp = sysv ;
>     if [ os.name ] = "NT" { tmp = ms ; }
>     else if [ os.name ] = "CYGWIN" { tmp = ms ; }
>     else if [ os.platform ] = "ARM" { tmp = aapcs ; }
>     else if ( [ os.platform ] = "MIPS" && <address-model>32 in $(properties) ) { tmp = o32 ; }
>     else if ( [ os.platform ] = "MIPS" && <address-model>64 in $(properties) ) { tmp = n64 ; }
>     return $(tmp) ;
> }
> ```

**Comment by wzssyqa** [comment]
> 
> 
> In build/Jamfile something like:
> 
> ```
> local rule default_abi ( properties * )
> {
>     local tmp = sysv ;
>     if [ os.name ] = "NT" { tmp = ms ; }
>     else if [ os.name ] = "CYGWIN" { tmp = ms ; }
>     else if [ os.platform ] = "ARM" { tmp = aapcs ; }
>     else if ( [ os.platform ] = "MIPS" && <address-model>32 in $(properties) ) { tmp = o32 ; }
>     else if ( [ os.platform ] = "MIPS" && <address-model>64 in $(properties) ) { tmp = n64 ; }

I have a try, while properties is empty here.

>     return $(tmp) ;
> }
> ```

**Comment by olk** [comment]
This PR is incomlete - it requires assembler for N64.
What's is the status of MIPS unification?

**Comment by FlyGoat** [comment]
@olk What's meant by unification?

**Comment by FlyGoat** [comment]
Ohhh I see I was doing that, it was never completed.

**Comment by olk** [comment]
Because it was never completed - should I close this PR?

**Comment by FlyGoat** [comment]
Cc: @wzssyqa for suggestion.

**Comment by wzssyqa** [comment]
> Cc: @wzssyqa for suggestion.

here is a dirty patch from Debian:
https://sources.debian.org/patches/boost1.74/1.74.0-9/fix_mipsel_asm_files.patch/

**Comment by wzssyqa** [comment]
I noticed that on i386-userland on amd64-kernel, the OSPLAT value is X86.
while mipsel-userland on mips64 kernel, the OSPLAT value is MIPS64.

where the value of
      static module_t root;
from?

**Comment by wzssyqa** [comment]
Index: boost1.74-1.74.0/tools/build/src/engine/jam.h
===================================================================
--- boost1.74-1.74.0.orig/tools/build/src/engine/jam.h
+++ boost1.74-1.74.0/tools/build/src/engine/jam.h
@@ -416,11 +416,12 @@
 #endif

 #ifdef __mips__
-  #if defined(_ABI64)
+  #if defined(_ABI64) && _MIPS_SIM == _ABI64
     #define OSPLAT "OSPLAT=MIPS64"
-  #elif defined(_ABIO32)
+  #elif defined(_ABIO32) && _MIPS_SIM == _ABIO32
     #define OSPLAT "OSPLAT=MIPS32"
   #endif
+  //TODO: support N32
 #endif

 #if defined( __arm__ ) || \


This patch can make it workable with mips32 with mips64 kernel.

**Comment by olk** [comment]
> ```
> Index: boost1.74-1.74.0/tools/build/src/engine/jam.h
> ===================================================================
> --- boost1.74-1.74.0.orig/tools/build/src/engine/jam.h
> +++ boost1.74-1.74.0/tools/build/src/engine/jam.h
> @@ -416,11 +416,12 @@
>  #endif
> 
>  #ifdef __mips__
> -  #if defined(_ABI64)
> +  #if defined(_ABI64) && _MIPS_SIM == _ABI64
>      #define OSPLAT "OSPLAT=MIPS64"
> -  #elif defined(_ABIO32)
> +  #elif defined(_ABIO32) && _MIPS_SIM == _ABIO32
>      #define OSPLAT "OSPLAT=MIPS32"
>    #endif
> +  //TODO: support N32
>  #endif
> ```
> 
> This patch can make it workable with mips32 with mips64 kernel.

Could you provide a Pull Request for boost.build, please?

**Comment by wzssyqa** [comment]
> > ```
> > Index: boost1.74-1.74.0/tools/build/src/engine/jam.h
> > ===================================================================
> > --- boost1.74-1.74.0.orig/tools/build/src/engine/jam.h
> > +++ boost1.74-1.74.0/tools/build/src/engine/jam.h
> > @@ -416,11 +416,12 @@
> >  #endif
> > 
> >  #ifdef __mips__
> > -  #if defined(_ABI64)
> > +  #if defined(_ABI64) && _MIPS_SIM == _ABI64
> >      #define OSPLAT "OSPLAT=MIPS64"
> > -  #elif defined(_ABIO32)
> > +  #elif defined(_ABIO32) && _MIPS_SIM == _ABIO32
> >      #define OSPLAT "OSPLAT=MIPS32"
> >    #endif
> > +  //TODO: support N32
> >  #endif
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This patch can make it workable with mips32 with mips64 kernel.
> 
> Could you provide a Pull Request for boost.build, please?

https://github.com/boostorg/build/commit/b97746e29cb1f4dc4cfd02bb6191441dbc0d39d8

This has been fixed.

**Comment by olk** [comment]
> This has been fixed.

And what is the TODO list for boost.context?

**Comment by wzssyqa** [comment]
> > This has been fixed.
> 
> And what is the TODO list for boost.context?

No real problem here, I guess.
and now we use `mips1` for all mips revision.

So should we switch `mips1` to `mips`?
This effects some boost projects.

**Comment by olk** [comment]
ty

**Pull request merged**
