### PR TITLE
Add support for modular build structure.

### PR DESCRIPTION
**Pull request by grafikrobot**
This is part of the effort to make the Boost libraries "modular" for build and consumption. See https://lists.boost.org/Archives/boost/2024/01/255704.php and https://github.com/grafikrobot/boost-b2-modular/blob/b2-modular/README.adoc for more information.

This PR depends on the following other PRs being merged to both develop and master branches of the respective repos:

- https://github.com/boostorg/boost/pull/854

This PR will be changed to ready for review, i.e. not draft, when the above are merged. Do not merge this one until that time.

### CODE REVIEW

**Comment by olk** [comment]
> Please review and merge this PR at your earliest convenience.

Sorry - some checks are faling (11 failing and 12 successful checks)

**Comment by olk** [comment]
Since https://github.com/boostorg/context/commit/463cffeac5fdaa712be316654a9e61b77cc358ec CI build are broken on some platforms!

**Comment by pdimov** [comment]
https://github.com/boostorg/predef/issues/137

**Comment by pdimov** [comment]
Did those CI jobs work when you originally wrote multi.yml? We need to figure out what broke them.

**Comment by pdimov** [comment]
https://github.com/boostorg/predef/issues/135 seems like a likely cause, too.

**Comment by pdimov** [comment]
OK, the answer is yes, they did work before this PR was merged: https://github.com/boostorg/context/actions/runs/10594678160

**Pull request merged**
